name: Generate test matrices pages

# Controls when the action will run.
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'
jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate the test matrix 🔧
        run: |
          go run cmd/main.go --debug gen_matrix

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
