name: Test the generation of test matrices pages

# Controls when the action will run.
on:
  pull_request:
    branches:
      - master
jobs:
  test-generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate the test matrix 🔧
        run: |
          sed -i 's/nb_test_history:.*/nb_test_history: 2/' examples/gpu-operator.yml
          sed -i 's/nb_test_history:.*/nb_test_history: 2/' examples/sro.yml
          make generate_daily_matrix
